### PR TITLE
feat: add support to read cert and keys from files

### LINKED ISSUE #6: Add support for reading the Key/Cert from the File
Currently we are suppoting pem string fromat for Key/Cert, 
Add support for reading key/cert from the file,
Add fields in the Idp config to take up the filePath from the root directory to read from that perticular file.

### PR DESCRIPTION
**Pull request by distributedlock**
Resolves #6.

Signed-off-by: Ranadeep Polavarapu <ranadeep@icloud.com>

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing](../../../CONTRIBUTING.md) document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by mayankagwl — COMMENTED** [review]
@RanadeepPolavarapu Looks good,
But as other PR also merged to master, can you please resolve conflict from the base branch.
Thanks

**Comment by distributedlock** [comment]
> @RanadeepPolavarapu Looks good,
> But as other PR also merged to master, can you please resolve conflict from the base branch.
> Thanks

@mayankagwl Great, thank you. I have resolved merge conflicts, fixed a few typos from the previous PR and `go fmt`. Ready for review.

**Comment by mayankagwl** [comment]
@RanadeepPolavarapu 
And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by distributedlock** [comment]
@mayankagwl Cheers, will do. Thank you. 😄

**Review by mayankagwl — APPROVED** [review]
Thanks @RanadeepPolavarapu

**Pull request merged**
